language: go

go:
  - 1.13.x

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq

env:
  - GO111MODULE=on AMQP_URL=amqp://guest:guest@localhost:5672/

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -cpu=1,2 -v ./... -tags integration -cover
  - $GOPATH/bin/goveralls -service=travis-ci
